// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDHfBtZ5m9P0nQcRFQs3FV9dH9cpMdEoTc',
    appId: '1:131692498389:web:564567087494e0e14ac15c',
    messagingSenderId: '131692498389',
    projectId: 'edge-46cf5',
    authDomain: 'edge-46cf5.firebaseapp.com',
    storageBucket: 'edge-46cf5.appspot.com',
    measurementId: 'G-R9BHR6PGZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAujBbNmE8HhjI-Zqv4Csob5jFAgiV7Ch0',
    appId: '1:131692498389:android:d0ae113a1880d64c4ac15c',
    messagingSenderId: '131692498389',
    projectId: 'edge-46cf5',
    storageBucket: 'edge-46cf5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKeD2sNm76GE6qCsFTU3oiiqAWgFFD3V0',
    appId: '1:131692498389:ios:a68621763284f7104ac15c',
    messagingSenderId: '131692498389',
    projectId: 'edge-46cf5',
    storageBucket: 'edge-46cf5.appspot.com',
    iosBundleId: 'com.example.collegeCommunityApk',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKeD2sNm76GE6qCsFTU3oiiqAWgFFD3V0',
    appId: '1:131692498389:ios:a68621763284f7104ac15c',
    messagingSenderId: '131692498389',
    projectId: 'edge-46cf5',
    storageBucket: 'edge-46cf5.appspot.com',
    iosBundleId: 'com.example.collegeCommunityApk',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDHfBtZ5m9P0nQcRFQs3FV9dH9cpMdEoTc',
    appId: '1:131692498389:web:a8b0fd2a2728a8ef4ac15c',
    messagingSenderId: '131692498389',
    projectId: 'edge-46cf5',
    authDomain: 'edge-46cf5.firebaseapp.com',
    storageBucket: 'edge-46cf5.appspot.com',
    measurementId: 'G-RB6DXRYCYQ',
  );
}
